name: telechat
description: Messenger app for Android and IOS.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  better_player: ^0.0.75
  cached_network_image: ^3.1.0
  clipboard: ^0.1.3
  collection: ^1.15.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  equatable: ^2.0.3
  extended_image: ^4.1.0
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.0
  flutter_bloc: ^7.3.0
  flutter_cache_manager: ^3.1.2
  flutter_contacts: ^1.1.0+3
  flutter_form_builder: ^6.1.0+1
  flutter_hooks: ^0.16.0
  flutter_image_compress: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^0.4.0
  fluttertoast: ^8.0.7
  get_it: ^6.0.0
  grouped_list: ^4.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.1
  image: ^3.0.2
  image_cropper: ^1.4.1
  injectable: ^1.1.2
  intl: ^0.17.0
  jiffy: ^4.1.0
  lint: ^1.5.3
  material_design_icons_flutter: ^4.0.5955
  permission_handler: ^8.1.4+2
  persian_tools: ^1.0.1
  photo_view: ^0.12.0
  responsive_framework: ^0.1.4
  scroll_to_index: ^2.0.0
  scrollable_positioned_list: ^0.1.10
  share_plus: ^2.1.4
  supabase: ^0.2.7
  universal_platform: ^1.0.0+1
  shamsi_date: ^0.15.0
  video_thumbnail: ^0.4.3

dev_dependencies:
  build_runner: null
  change_app_package_name: ^0.1.3
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  injectable_generator: ^1.1.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/telechat_logo.jpg"

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Light-UI.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Regular-UI.ttf
          weight: 400
        - asset: assets/fonts/Vazir-Medium-UI.ttf
          weight: 500
        - asset: assets/fonts/Vazir-Bold-UI.ttf
          weight: 700
